class CacheException(Exception):
  def __init__(self):
    pass